//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameCollector.DataHandlers.TheGamesDb.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameCollector.DataHandlers.TheGamesDb.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;code&quot;:200,&quot;status&quot;:&quot;Success&quot;,&quot;data&quot;:{&quot;count&quot;:7968,&quot;developers&quot;:{&quot;142&quot;:{&quot;id&quot;:142,&quot;name&quot;:&quot;?&quot;},&quot;9916&quot;:{&quot;id&quot;:9916,&quot;name&quot;:&quot;.dat&quot;},&quot;2&quot;:{&quot;id&quot;:2,&quot;name&quot;:&quot;.theprodukkt&quot;},&quot;9898&quot;:{&quot;id&quot;:9898,&quot;name&quot;:&quot;[adult swim] games&quot;},&quot;9899&quot;:{&quot;id&quot;:9899,&quot;name&quot;:&quot;[bracket]games&quot;},&quot;9900&quot;:{&quot;id&quot;:9900,&quot;name&quot;:&quot;[erka:es]&quot;},&quot;9901&quot;:{&quot;id&quot;:9901,&quot;name&quot;:&quot;][ Games Inc&quot;},&quot;145&quot;:{&quot;id&quot;:145,&quot;name&quot;:&quot;@nifty&quot;},&quot;10341&quot;:{&quot;id&quot;:10341,&quot;name&quot;:&quot;~JV~&quot;},&quot;3&quot;:{&quot;id&quot;:3,&quot;name&quot;:&quot;07th Expansion&quot;},&quot;4&quot;:{&quot;id&quot;:4,&quot;name&quot;:&quot;1-Pup Games&quot;},&quot;5&quot;:{&quot;id&quot;:5,&quot;name&quot;:&q....
        /// </summary>
        internal static string tgdb_developers {
            get {
                return ResourceManager.GetString("tgdb_developers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;code&quot;:200,&quot;status&quot;:&quot;Success&quot;,&quot;data&quot;:{&quot;count&quot;:4269,&quot;publishers&quot;:{&quot;2374&quot;:{&quot;id&quot;:2374,&quot;name&quot;:&quot;.GEARS Studios&quot;},&quot;2090&quot;:{&quot;id&quot;:2090,&quot;name&quot;:&quot;1-Pup Games&quot;},&quot;4045&quot;:{&quot;id&quot;:4045,&quot;name&quot;:&quot;10 out of 10&quot;},&quot;5898&quot;:{&quot;id&quot;:5898,&quot;name&quot;:&quot;10Ants Hill&quot;},&quot;3542&quot;:{&quot;id&quot;:3542,&quot;name&quot;:&quot;10tons Ltd.&quot;},&quot;1188&quot;:{&quot;id&quot;:1188,&quot;name&quot;:&quot;11 bit studios&quot;},&quot;2557&quot;:{&quot;id&quot;:2557,&quot;name&quot;:&quot;1337 &amp; Senri LLC&quot;},&quot;4313&quot;:{&quot;id&quot;:4313,&quot;name&quot;:&quot;13AM Games&quot;},&quot;3796&quot;:{&quot;id&quot;:3796,&quot;name&quot;:&quot;17-BIT&quot;},&quot;3610&quot;:{&quot;id&quot;:3610,&quot;name&quot;:&quot;1985 Alternativo&quot;},&quot;402&quot;:{&quot;id&quot;:402,&quot;name&quot;:&quot;1C Company&quot; [res....
        /// </summary>
        internal static string tgdb_publishers {
            get {
                return ResourceManager.GetString("tgdb_publishers", resourceCulture);
            }
        }
    }
}
